/**
 * Mapeamento: nome do país em português → código ISO 3166-1 alpha-2
 * Usado para carregar bandeiras via flagcdn.com/{code}.png
 */
export const COUNTRY_ISO: Record<string, string> = {
  'África do Sul': 'za',
  'Alemanha': 'de',
  'Arábia Saudita': 'sa',
  'Argélia': 'dz',
  'Argentina': 'ar',
  'Austrália': 'au',
  'Áustria': 'at',
  'Bélgica': 'be',
  'Bósnia e Herzegovina': 'ba',
  'Brasil': 'br',
  'Cabo Verde': 'cv',
  'Camarões': 'cm',
  'Canadá': 'ca',
  'Catar': 'qa',
  'Chile': 'cl',
  'China': 'cn',
  'Colômbia': 'co',
  'Coreia do Norte': 'kp',
  'Coreia do Sul': 'kr',
  'Costa do Marfim': 'ci',
  'Costa Rica': 'cr',
  'Croácia': 'hr',
  'Curaçao': 'cw',
  'Dinamarca': 'dk',
  'Egito': 'eg',
  'Equador': 'ec',
  'Escócia': 'gb-sct',
  'Espanha': 'es',
  'Estados Unidos': 'us',
  'França': 'fr',
  'Gana': 'gh',
  'Grécia': 'gr',
  'Guatemala': 'gt',
  'Haiti': 'ht',
  'Holanda': 'nl',
  'Honduras': 'hn',
  'Inglaterra': 'gb-eng',
  'Irã': 'ir',
  'Iraque': 'iq',
  'Irlanda': 'ie',
  'Islândia': 'is',
  'Israel': 'il',
  'Itália': 'it',
  'Jamaica': 'jm',
  'Japão': 'jp',
  'Jordânia': 'jo',
  'Kuwait': 'kw',
  'Marrocos': 'ma',
  'México': 'mx',
  'Nigéria': 'ng',
  'Noruega': 'no',
  'Nova Zelândia': 'nz',
  'Omã': 'om',
  'Panamá': 'pa',
  'Paraguai': 'py',
  'Peru': 'pe',
  'Polônia': 'pl',
  'Portugal': 'pt',
  'RD Congo': 'cd',
  'República Tcheca': 'cz',
  'República Dominicana': 'do',
  'Rússia': 'ru',
  'Senegal': 'sn',
  'Sérvia': 'rs',
  'Suécia': 'se',
  'Suíça': 'ch',
  'Trinidad e Tobago': 'tt',
  'Tunísia': 'tn',
  'Turquia': 'tr',
  'Ucrânia': 'ua',
  'Uruguai': 'uy',
  'Uzbequistão': 'uz',
  'Venezuela': 've',
}

export function countryNameToIso(name: string): string {
  return COUNTRY_ISO[name] ?? ''
}
